# Composition for development

version: '2'

services:
  odoo:
    build: ./odoo/
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=Insidjam2017
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - LOG_HANDLER=:WARN

  db:
    image: camptocamp/postgresql:pg9.5-latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "data-db:/var/lib/postgresql/data"

  # can be useful for dev when longpolling is required
#  nginx:
#    image: camptocamp/odoo-nginx:9.0
#    depends_on:
#      - odoo

volumes:
  data-odoo:
  data-db:
